<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Sunday, May 11, 2025 11:55:32 PM</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "F:\OneDrive - Louisiana State University\LSU_Course\GEOG\GEOG 4057 GIS Programming\GEOG4057_Hanqi\Projects\Project_2_Hanqi\ArcgisPro_Proj2\ArcgisPro_Proj2.atbx\Proj2Tool.tool\tool.script.execute.py", line 63, in &lt;module&gt;
﻿  File "F:\OneDrive - Louisiana State University\LSU_Course\GEOG\GEOG 4057 GIS Programming\GEOG4057_Hanqi\Projects\Project_2_Hanqi\ArcgisPro_Proj2\ArcgisPro_Proj2.atbx\Proj2Tool.tool\tool.script.execute.py", line 26, in getGeeElevation
﻿  File "C:\Users\hli69\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\ee\computedobject.py", line 28, in __call__
﻿    return type.__call__(cls, *args, **kwargs)
﻿           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "C:\Users\hli69\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\ee\deprecation.py", line 124, in Wrapper
﻿    return func(*args, **kwargs)
﻿           ^^^^^^^^^^^^^^^^^^^^^
﻿  File "C:\Users\hli69\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\ee\image.py", line 75, in __init__
﻿    self.initialize()
﻿  File "C:\Users\hli69\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\ee\image.py", line 121, in initialize
﻿    apifunction.ApiFunction.importApi(cls, cls.name(), cls.name())
﻿  File "C:\Users\hli69\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\ee\_utils.py", line 38, in wrapper
﻿    return func(*args, **kwargs)
﻿           ^^^^^^^^^^^^^^^^^^^^^
﻿  File "C:\Users\hli69\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\ee\apifunction.py", line 197, in importApi
﻿    cls.initialize()
﻿  File "C:\Users\hli69\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\ee\apifunction.py", line 161, in initialize
﻿    signatures = data.getAlgorithms()
﻿                 ^^^^^^^^^^^^^^^^^^^^
﻿  File "C:\Users\hli69\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\ee\data.py", line 1481, in getAlgorithms
﻿    _get_cloud_projects()
﻿  File "C:\Users\hli69\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\ee\data.py", line 352, in _get_cloud_projects
﻿    raise ee_exception.EEException(_NOT_INITIALIZED_MESSAGE)
﻿ee.ee_exception.EEException: Earth Engine client library not initialized. See http://goo.gle/ee-auth.
</msg><msg code="0" type="0">Failed script Script...</msg><msg code="-2147467259" type="100">Failed to execute (Proj2Tool).</msg><msg code="0" type="3">Failed at Sunday, May 11, 2025 11:55:46 PM (Elapsed Time: 14.11 seconds)</msg></messages>